import type { QuestionPreview } from "@/types/ui";

export const mockQuestions: QuestionPreview[] = [
  {
    id: "q-1",
    text: "Evaluate the integral \\int_0^{\\pi/2} \\sin^3 x \\cos^2 x \\, dx using reduction formulae.",
    difficulty: "medium",
    type: "short",
    marks: 5,
    source: "DTU",
    year: 2025,
    topic: "Integration Techniques",
    solved: false,
    bookmarked: true,
  },
  {
    id: "q-2",
    text: "Find the eigenvalues and eigenvectors of the matrix A = \\begin{pmatrix} 2 & 1 \\\\ 1 & 2 \\end{pmatrix}.",
    difficulty: "easy",
    type: "short",
    marks: 4,
    source: "DTU",
    year: 2024,
    topic: "Eigenvalues and Eigenvectors",
    solved: true,
    bookmarked: false,
  },
  {
    id: "q-3",
    text: "Solve the differential equation (x^2 + y^2)dx - 2xy\\,dy = 0 using the substitution y = vx.",
    difficulty: "hard",
    type: "proof",
    marks: 7,
    source: "DTU",
    year: 2025,
    topic: "First Order Differential Equations",
    solved: false,
    bookmarked: false,
  },
  {
    id: "q-4",
    text: "Find the Laplace transform of f(t) = t^2 e^{-3t}.",
    difficulty: "medium",
    type: "numerical",
    marks: 5,
    source: "DTU",
    year: 2023,
    topic: "Laplace Transform",
    solved: false,
    bookmarked: false,
  },
  {
    id: "q-5",
    text: "Verify Stokes' theorem for F = (y, -x, 0) over the upper hemisphere x^2 + y^2 + z^2 = 1, z \\geq 0.",
    difficulty: "hard",
    type: "proof",
    marks: 8,
    source: "DTU",
    year: 2024,
    topic: "Gradient, Divergence and Curl",
    solved: false,
    bookmarked: true,
  },
];
