import katex from "katex";
import "katex/dist/katex.min.css";

export type MathProps = {
  /** LaTeX source, e.g. "x^2 + y^2 = r^2" */
  tex: string;
  /** Block (centered, own line) vs inline. Defaults to inline. */
  display?: boolean;
  className?: string;
};

/**
 * Renders LaTeX via KaTeX. This is the only sanctioned way to render maths in
 * the app (per CLAUDE.md) — never render raw user LaTeX through any other path.
 *
 * throwOnError is false so a malformed string renders KaTeX's own inline error
 * span instead of crashing the page, and output "htmlAndMathml" keeps a MathML
 * annotation alongside the visual HTML for screen readers.
 */
export function Math({ tex, display = false, className }: MathProps) {
  const html = renderTexSafely(tex, display);
  const Tag = display ? "div" : "span";

  return (
    <Tag
      className={className}
      // html is generated by katex.renderToString below, never raw user input.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function renderTexSafely(tex: string, display: boolean): string {
  try {
    return katex.renderToString(tex, {
      throwOnError: false,
      displayMode: display,
      output: "htmlAndMathml",
      strict: "warn",
      trust: false,
    });
  } catch {
    // katex.renderToString should not throw with throwOnError: false, but
    // fall back to an escaped, visibly-flagged version rather than crash.
    return `<span class="text-destructive">Invalid maths expression</span>`;
  }
}
